AWSTemplateFormatVersion: '2010-09-09'

Description: 'FunctionCI is an open source CI/CD Slack Bot for AWS Lambdas.'

Parameters:
  KMSStack:
    Type: String
    Description: KMS Stack Name
    Default: 'functionci-kms'
  TLD:
    Type: String
    Description: TLD name needed by Route53 to perform DNS (example.com)
    Default: ''
  Domain:
    Type: String
    Description: Domain name for your api (api.example.com)
    Default: ''
  Path:
    Type: String
    Description: The path part of your api (api.example.com/path)
    Default: 'api'
  Stage:
    Type: String
    Description: The deployment stage used by API Gateway
    Default: 'prod'
  SlackVerificationToken:
    Type: String
    Description: Slack verification token
    NoEcho: true
  SlackBotOAuthToken:
    Type: String
    Description: Slack Bot OAuth Token
    NoEcho: true
  GithubToken:
    Type: String
    Description: Github Token
    NoEcho: true

Conditions:
  UseCustomDomain: !And
    - !Not [!Equals [!Ref TLD, '']]
    - !Not [!Equals [!Ref Domain, '']]

Resources:

  #
  # Role for CloudFormation
  #
  IamRoleCloudFormationExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

  #
  # Create a Policy and attach it to our CloudFormation Role.
  #
  IamPolicyCloudFormationExecution:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: IamPolicyCloudFormationExecution
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - cloudformation:CreateStack
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResources
            - cloudformation:GetTemplate
            - cloudformation:ValidateTemplate
          Resource: '*'
        - Effect: Allow
          Action:
            - iam:Create*
            - iam:List*
            - iam:Put*
            - iam:Get*
            - iam:Attach*
            - iam:Detach*
            - iam:Delete*
            - iam:Pass*
          Resource: '*'
        - Effect: Allow
          Action:
            - logs:*
          Resource: '*'
        - Effect: Allow
          Action:
            - codepipeline:*
          Resource: '*'
        - Effect: Allow
          Action:
            - codebuild:*
          Resource: '*'
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: '*'
        - Effect: Allow
          Action:
            - events:*
          Resource: '*'
        - Effect: Allow
          Action:
            - lambda:*
          Resource: '*'
      Roles:
      - Ref: IamRoleCloudFormationExecution

  #
  # DynamoDB Tables
  #
  FunctionCITable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'FunctionCI'
      AttributeDefinitions:
        -
          AttributeName: 'hash_key'
          AttributeType: 'S'
        -
          AttributeName: 'sort_key'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'hash_key'
          KeyType: 'HASH'
        -
          AttributeName: 'sort_key'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'functionci-artifacts'

  #
  # Role that our Lambda will assume to provide access to other AWS resources
  #
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

  #
  # Create a Policy and attach it to our Lambda Role.
  #
  IamPolicyLambdaExecution:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: IamPolicyLambdaExecution
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - codebuild:ListCuratedEnvironmentImages
          Resource: '*'
        - Effect: Allow
          Action:
            - iam:GetRole
            - iam:PassRole
          Resource: !GetAtt IamRoleCloudFormationExecution.Arn
        - Effect: Allow
          Action:
            - lambda:UpdateFunctionCode
            - lambda:UpdateAlias
            - lambda:ListAliases
            - lambda:ListVersionsByFunction
            - lambda:DeleteFunction
            - lambda:PublishVersion
          Resource: '*'
        - Effect: Allow
          Action:
            - codepipeline:*
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: !GetAtt FunctionCITable.Arn
        - Effect: Allow
          Action:
            - cloudformation:CreateStack
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResources
            - cloudformation:GetTemplate
            - cloudformation:ValidateTemplate
            - cloudformation:DeleteStack
          Resource: '*'
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: ArtifactsBucket
            - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: ArtifactsBucket
                  - '/*'
      Roles:
      - Ref: IamRoleLambdaExecution

  #
  # Our Lambda function.  Basic code has been added.  You will replace the code later via your Github repo.
  #
  LambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - IamRoleCloudFormationExecution
      - IamPolicyCloudFormationExecution
      - FunctionCITable
      - SNSTopic
      - ArtifactsBucket
    Properties:
      Handler: index.handler
      Timeout: 5
      Role:
        Fn::GetAtt:
          - IamRoleLambdaExecution
          - Arn
      Code:
        ZipFile: !Sub |
          'use strict';

          exports.handler = function(event, context, callback) {
              const response = {
                  statusCode: 200,
                  body: JSON.stringify({
                      message: `Hello CIM`,
                      event: event
                  })
              };

              callback(null, response);
          };
      Runtime: nodejs6.10
      KmsKeyArn:
        Fn::ImportValue:
          !Sub "${KMSStack}-FunctionCiKmsKeyArn"
      Environment:
        Variables:
          IamRoleCloudFormationExecution: !GetAtt IamRoleCloudFormationExecution.Arn
          FunctionCITable: !Ref FunctionCITable
          SNSTopic: !Ref SNSTopic
          SlackVerificationToken: !Ref SlackVerificationToken
          SlackBotOAuthToken: !Ref SlackBotOAuthToken
          GithubToken: !Ref GithubToken
          ArtifactsBucket: !Ref ArtifactsBucket

  #
  # 'PROD' Alias -> Version 1
  #
  LambdaFunctionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LambdaFunction
      FunctionVersion: !GetAtt LambdaFunctionVersion.Version
      Name: 'PROD'
  
  #
  # Create Lambda Version
  #
  LambdaFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunction

  #
  # Create the API Gateway
  #
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ApiGatewayRestApi

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: !Ref Path #ex. example.com/api.
      RestApiId: !Ref RestApi

  ApiGatewayResourceProxy:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiGatewayResource
      PathPart: '{proxy+}'
      RestApiId: !Ref RestApi

  ApiGatewayMethodOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      ResourceId: !Ref ApiGatewayResourceProxy
      RestApiId: !Ref RestApi
      HttpMethod: OPTIONS
      Integration:
        IntegrationResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
            method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Credentials: "'false'"
          ResponseTemplates:
            application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: 'Empty'
        ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: false
            method.response.header.Access-Control-Allow-Methods: false
            method.response.header.Access-Control-Allow-Origin: false
            method.response.header.Access-Control-Allow-Credentials: true

  ApiGatewayMethodAny:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      RequestParameters: {}
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: AWS::Region
              - ':lambda:path/2015-03-31/functions/'
              - !GetAtt LambdaFunction.Arn
              - '/invocations'
      MethodResponses: []

  ApiGatewayMethodProxyAny:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      RequestParameters: {}
      ResourceId: !Ref ApiGatewayResourceProxy
      RestApiId: !Ref RestApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ''
            - - 'arn:aws:apigateway:'
              - Ref: AWS::Region
              - ':lambda:path/2015-03-31/functions/'
              - !GetAtt LambdaFunction.Arn
              - '/invocations'
      MethodResponses: []

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: !Ref Stage # Maps to the custom domain name.  BasePathMapping.Stage
    DependsOn:
      - ApiGatewayMethodOptions
      - ApiGatewayMethodAny
      - ApiGatewayMethodProxyAny

  #
  # We need to give API Gateway permission to invoke our Lambda function.
  #
  PermissionForAPIGatewayToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':'
            - Ref: RestApi
            - '/*/*'

  #
  # SSL Certificate needed by CloudFront.
  #
  SSL:
    Type: AWS::CertificateManager::Certificate
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          ValidationDomain: !Ref TLD

  #
  # Custom Domain Name
  #
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref Domain
      CertificateArn: !Ref SSL

  #
  # Wire custom domain to Api Gateway
  #
  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref RestApi
      Stage: !Ref Stage

  #
  # Route53 DNS record set to map our domain to API Gateway
  #
  DomainDNS:
    Type: AWS::Route53::RecordSetGroup
    Condition: UseCustomDomain
    Properties:
      HostedZoneName:
        Fn::Join:
          - ''
          - - !Ref TLD
            - '.'
      RecordSets:
        -
          Name: !Ref Domain
          Type: 'A'
          AliasTarget:
            HostedZoneId: 'Z2FDTNDATAQYW2' # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
            DNSName: !GetAtt ApiDomainName.DistributionDomainName


  #
  # SNS Topic
  #
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Fn::Join:
          - ''
          - - Ref: AWS::StackName
            - ' Topic'
      TopicName:
        Fn::Join:
          - ''
          - - Ref: AWS::StackName
            - '-topic'

  #
  # Subscribe our new Lambda function to the SNS topic.
  #
  LambdaSNSSubscription:
    Type: AWS::SNS::Subscription
    DependsOn: LambdaFunction
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: lambda
      Endpoint: !GetAtt LambdaFunction.Arn

  #
  # Give SNS permission to invoke our Lambda
  #
  PermissionForSNSToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref SNSTopic

Outputs:
  LambdaFunction:
    Description: Lambda Function
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunction'
  LambdaFunctionArn:
    Description: Lambda Function Arn
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'
  ArtifactsBucket:
    Description: Artifacts Bucket
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactsBucket'
  ApiGatewayUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - 'https://'
        - !Ref RestApi
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/'
        - !Ref Stage
        - '/'
        - !Ref Path
  SlackSlashCommandsUrl:
    Description: Slack slash commands url
    Value: !Join
      - ''
      - - 'https://'
        - !Ref RestApi
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/'
        - !Ref Stage
        - '/'
        - !Ref Path
        - '/commands'
  SlackInteractiveComponentsUrl:
    Description: Slack interactive components url
    Value: !Join
      - ''
      - - 'https://'
        - !Ref RestApi
        - '.execute-api.'
        - !Ref AWS::Region
        - '.amazonaws.com/'
        - !Ref Stage
        - '/'
        - !Ref Path
        - '/interactive-components'
  CustomDomainUrl:
    Description: URL of your API endpoint
    Condition: UseCustomDomain
    Value: !Join
      - ''
      - - 'https://'
        - !Ref Domain
        - '/'
        - !Ref Path
  CustomSlackSlashCommandsUrl:
    Description: Slack slack commands url
    Condition: UseCustomDomain
    Value: !Join
      - ''
      - - 'https://'
        - !Ref Domain
        - '/'
        - !Ref Path
        - '/commands'
  CustomSlackInteractiveComponentsUrl:
    Description: Slack interactive components url
    Condition: UseCustomDomain
    Value: !Join
      - ''
      - - 'https://'
        - !Ref Domain
        - '/'
        - !Ref Path
        - '/interactive-components'
